<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc/4.0/88x31.png" /></a><br /><span xmlns:dct="http://purl.org/dc/terms/" property="dct:title">Introduction to quantum mechanics</span> by <span xmlns:cc="http://creativecommons.org/ns#" property="cc:attributionName">Dr Juan H Klopper</span> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/">Creative Commons Attribution-NonCommercial 4.0 International License</a>.

In [2]:
from IPython.core.display import HTML, Image
css_file = 'style.css'
HTML(open(css_file, 'r').read())

In [82]:
from scipy import matrix, sqrt
from scipy.linalg import eig
from warnings import filterwarnings
filterwarnings("ignore")

<h1>
Eigenvalues and eigenvectors
</h1>

<h2>Square matrices</h2>

In this section we will be given a square matrix that has a special property.  In order to look at this property, we need to know what an adjoint of a matrix is.  Well, its is simply the transpose of the matrix with every element changed to its complex conjugate (see more in next chapter).<br/>
If the adjoint of a matrix is exactely the same as the matrix itself, we call the matrix *Hermetian*.

In [57]:
# Creating the square matrix
A = matrix([[2, 2 + 1j], [2- 1j, 4]])
A

matrix([[ 2.+0.j,  2.+1.j],
        [ 2.-1.j,  4.+0.j]])

In [58]:
# The transpose of A
A.transpose()

matrix([[ 2.+0.j,  2.-1.j],
        [ 2.+1.j,  4.+0.j]])

In [59]:
# The conjoint of A
A.getH()

matrix([[ 2.-0.j,  2.+1.j],
        [ 2.-1.j,  4.-0.j]])

In [60]:
# Checking to see of A is Hermetian
A == A.getH()

matrix([[ True,  True],
        [ True,  True]], dtype=bool)

In [61]:
# Calculating the eigenvalues and eigenvectors of A
eigenval, eigenvec = eig(A)
eigenval, eigenvec

(array([ 0.55051026 -1.50231211e-17j,  5.44948974 -2.07021484e-16j]),
 array([[ 0.83912106+0.j        ,  0.48651894+0.24325947j],
        [-0.48651894+0.24325947j,  0.83912106+0.j        ]]))

In [62]:
# The first eigenvalue (the solution is a tuple) and indexing starts at 0
eigenval[0]

(0.55051025721682167-1.5023121074764078e-17j)

In [63]:
# The first eigenvector (have to reshape because it is returned as an array)
eigenvec[:,0].reshape(2, 1)

array([[ 0.83912106+0.j        ],
       [-0.48651894+0.24325947j]])

In [64]:
# Matrix times first eigenvectors
A * eigenvec[:,0].reshape(2, 1)

matrix([[ 0.46194475+0.j        ],
        [-0.26783367+0.13391683j]])

In [65]:
# Eigenvalue times eigenvector
eigenval[0] * eigenvec[:,0].reshape(2, 1)

array([[ 0.46194475 -1.26062172e-17j],
       [-0.26783367 +1.33916835e-01j]])

Within rounding errors, these two values are the same.

We can look at what happens with a non-Hermetian matrix.

In [66]:
A = matrix([[1, 3], [2, -4]])
A

matrix([[ 1,  3],
        [ 2, -4]])

In [67]:
# The conjoint of the matrix
A.getH()

matrix([[ 1,  2],
        [ 3, -4]])

In [68]:
# Eigenvalues and eigenvectors (displaying first of each)
eigenvals, eigenvects = eig(A)
eigenvals[0], eigenvects[:, 0].reshape(2, 1)

((2+0j), array([[ 0.9486833 ],
        [ 0.31622777]]))

In [69]:
# A times first eigenvector
A * eigenvects[:,0].reshape(2, 1)

matrix([[ 1.8973666 ],
        [ 0.63245553]])

In [70]:
# First eigenvalue times first eigenvector
eigenvals[0] * eigenvects[:,0].reshape(2, 1)

array([[ 1.89736660+0.j],
       [ 0.63245553+0.j]])

So, we note something very nice about multiplying a square matrix times one of its eigenvectors.  It is the same as multiplying the corresponding eigenvalue times the eigenvector, i.e. $A\left|v\right> = \lambda\left|v\right>$.<br/>
*Eigen* is a German word meaning *innate* or *natural*.<br/>
If you consider this carefully it says that a (square) matrix operating on one of its eigenvectors results in a scalar multiple of that eigenvector.  So, it is only the magnitude of the eigenvector that changes (that is to say if teh eigenvalue is not 1).

<h2>Taking a closer look at the Hermitian matrix</h2>

Let's take another look at a (Hermitian) matrix.  There is something perculiar about its eigenvalues and eigenvectors.

Let's do this bit in sympy.

In [80]:
from sympy import init_printing, Matrix, I, sqrt
from sympy.physics.quantum import Dagger
init_printing(use_latex = "mathjax")

In [99]:
A = Matrix([[2, 1], [1, 2]])
A

⎡2  1⎤
⎢    ⎥
⎣1  2⎦

In [100]:
Dagger(A)

⎡2  1⎤
⎢    ⎥
⎣1  2⎦

In [101]:
Dagger(A) == A

True

Let's look at the two eigenvalues and eigenvalues.

In [102]:
A.eigenvals()

{1: 1, 3: 1}

In [103]:
A.eigenvects()

⎡⎛1, 1, ⎡⎡-1⎤⎤⎞, ⎛3, 1, ⎡⎡1⎤⎤⎞⎤
⎢⎜      ⎢⎢  ⎥⎥⎟  ⎜      ⎢⎢ ⎥⎥⎟⎥
⎣⎝      ⎣⎣1 ⎦⎦⎠  ⎝      ⎣⎣1⎦⎦⎠⎦

Let's get the inner product of the two eigenvectors.  Remember the following mathematics.  $$\underline{a}\cdot\underline{b}={\underline{b}}^{T}\times\underline{a}$$
Since the eigenvectors contain complex numer elements, we have to get the adjoint of the second eigenvector when doing this innerproduct.

In [105]:
eigenvec1 = Matrix([[-1], [1]])
eigenvec2 = Matrix([[1], [1]])

In [106]:
Dagger(eigenvec2) * eigenvec1

[0]

They are orthogonal by virtue of the fact that their innerproduct is zero.<br/>
They can also be normalized so that their inner products with themselves can be evaluated (to see if it is equal to 1), as in $\left<\psi|\psi\right>=1$

In [108]:
eigenvec1n = eigenvec1.normalized()
eigenvec2n = eigenvec2.normalized()

In [111]:
Dagger(eigenvec1n) * eigenvec1n

[1]

In [113]:
Dagger(eigenvec2n) * eigenvec2n

[1]

The eigenvectors are thus orthonormal basis vectors.